language: python
python:
- '3.9'
env:
  global:
  - DJANGO_SETTINGS_MODULE=mysite.settings
  - AWS_DEFAULT_REGION=us-west-2
  - secure: ilSLqUSKttIZBixJkOrXtdpiZ//MMlagU9wS4AdmDIjjI0W2fX1QIxugiqkuFVSNSv2Q4Yjp7h5Y53A3IES0HF1xHJqD09gu7LAx/lnQdJr0PBzMi0iFloCj5ftXk8FMg47wb+teXDmnVMUznp12HNroMxtdlaWAE0clYGSaPJl6bP0gjfGmYGjEFqHnoBHAoMt5Ko+7Srw7uU32BZX3aFQAxIzr9YjC+x11d1ZQylQNqmFTEPFeASxqN1ebniRoCbS21joIxj8F559/EgN/WMTLFIMb/UATKeLf2s9XnHS24LrcNxnS3oLvuIzvqa8yFSDxg3g4FgQ1wCR8KlGocQJ6B6WncO4kDWUcrQiC07lG0pJ1qVK6UQbj1rOmCFUgNgRrKPFKWZh8RAdCPRRyJjpRLiVCu0WgL/XvSguPiv4f9rjfSEU3/fEDSrZJNc66WWkMIn1uHtaPsbF1qacbn4VjB1I09gJeG8LSIthNFWMBfn7dr9wHky7Z0x3qhPBHgU0ksy3LqdZn/QzTf6iDMrxlxi/YvW1UfBr+JggdNqnsvPAugWLGDoroEWK2VYj3OYpEb3sxGnTekV+Z91/fsgnT+LsTIAkCjYM4sL73DwptQpZaz5Z2KZWOLG5377u//hr21KpaxqVBPPvpL0MQjVJJZYTSZHBV7BwNYQAGz8w=
  - secure: i3GY93UDgA6mBCoimAGjuI9Mw+MRB6enlBycmtFSrtmy5g5TJ0/2G/7JCOoiD8p7waQKvT9qQj94uV638Dk7k8288zfe4cq2ga8K9jT5zPseKp0oZuSQklYrr1gfYEmTRQpUCBmoH+uAfhLXeTqURbyT6tZRvp/Toyie5e5IbxI+DIGYLPyGi2peOH/wkzW1MeSCsnuLiWaJ3MQXENeMg80DN/f3pVl7hlLgHUOFEk3njwBP8ACGMpzyqL2/VBM3UikU5J7i+xN+kMBSAO1nhAV999e4yaAwujaEmn0U/5WNqI+exN0YVtZ+GolAIO1QuO1MaYSpeWdK03ofFqsih9IL979j5yvTHDVK14Hd+ENL+IqboKjwKATWU8wTJqYTcUjelfXH+Da79yOS9ZyV02k0PIfJqTykGdjzIqDIpE5LGt+V98ryHNmcdPFKFlrL6mFUMz6HPMvltytp6fEryPiWi9AwZgT6orMbbBEhxRUk3P3WGsvRKf+6pr/e4RENamsQkcpu2R7JQIerfn/tBuCuzEEoOJqbC1JemfNGuEcU0iywpFATAoRWPKsOaBZCQAG3nKKU7Isirugomav3cuQt/hYfuDIsEysR1R1+XIrjD4mYvgGIkQizmoAPpOD5r05yUrChVYgBqYPz4t7QrWRVb4tx+QkaQ3pNmiSINuQ=
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install awscli awsebcli pytest
- pip install coveralls  # Add this line

script:
- coverage run --source='.' manage.py test polls  # Use coverage to run tests
- coverage report  # Optional: to see the coverage report in the console
- coveralls  # Send coverage data to Coveralls

repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.9

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_DEFAULT_REGION"
  app: django-tutorial
  env: django-tutorial-env
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    all_branches: true
