language: python
python:
- '3.9'
env:
  global:
  - DJANGO_SETTINGS_MODULE=mysite.settings
  - AWS_DEFAULT_REGION=us-west-2
  - secure: OQ7VKfbFPrB03EM//YO+03FttFCFKJ2TFyGkXwXGth+GqB493W9FTW2wgU6sanGVsuaGxO9xwVof9nmKsqRXm21thGuKMRe2BZZK6qFgf0ux+oP0CwBSxZCMjSAaZYDStaMLU10lTbOcnxUPQHTNDgNFNTK9lHL/qhK/PIf+0rbOX45C5KP2aPBTLvW6TejYMkCoEuEOmci2K0KnKcW5eiuD3eeUeVmW1vKA36MNwdqR6xUix214j++fssf9G+7ShDxRAeAxyjweL+9e52w2IK94f3pISMtTUY36fi4xYu7dUld+1EoSoANMvIuj9Ps032hA8GCQY6PoJshB00YmYkyblls6DCro64D6moLFEonQ4zTyXZPxGOG7xCfdQ/mhzmeMtunz7olQFfIkZvMmEky1sklASZ6DYN3rurE5i/T+iCE7Sv8jygiQOBJGLBLfMaho4IHXvt6qBfVpKoqMXrVfBsJlh3X3ZHDPq4iGSz8Mq9dwQ1mKk3NSYpPatiyM3QOzb1GDKL8Vj3lRjN3kmOf/E78ZFBkIqluDUPOG1pSc1g9h7LxeDDsRG47w8TwO2qGunnSvm/241lwkPAoKczX4WOe+QEaI3WbItN//IsgzGcs1lEdU8nd9GJp17yEEv+McUMu/wCwTZoBSEUzGjZykspJ2gixQoyNH1ZVRyBE=

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install awscli awsebcli pytest

script:
- python manage.py test polls

before_deploy:
- eb init django-tutorial -p python-3.9 --region $AWS_DEFAULT_REGION
- eb create django-env --database.engine django.db.backends.sqlite3 || eb use django-env

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_DEFAULT_REGION"
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    all_branches: true