language: python
python:
- '3.9'
env:
  global:
  - DJANGO_SETTINGS_MODULE=mysite.settings
  - AWS_DEFAULT_REGION=us-west-2
  - secure: YOUR_ENCRYPTED_KEYS_HERE

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install awscli awsebcli pytest

script:
- python manage.py test polls

before_deploy:
- eb init django-tutorial -p python-3.9 --region $AWS_DEFAULT_REGION
- eb create django-env --database.engine django.db.backends.sqlite3 || eb use django-env

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_DEFAULT_REGION"
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    all_branches: true